"""Generate Roblox data and a reviewable content inventory from catalog.json."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def lua(value, depth=0):
    pad = "    " * depth
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "{" + ", ".join(lua(v, depth + 1) for v in value) + "}"
    return "{\n" + "\n".join(pad + "    [" + lua(k) + "] = " + lua(v, depth + 1) + "," for k, v in value.items()) + "\n" + pad + "}"

def generate():
    data = json.loads((ROOT / "data/catalog.json").read_text(encoding="utf-8"))
    target = ROOT / "src/shared/Content.luau"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("-- Generated by scripts/generate_content.py; edit data/catalog.json.\nreturn " + lua(data) + "\n", encoding="utf-8")
    lines = ["# Content inventory", "", "Generated from data/catalog.json. All timings, damage, and mechanical adaptations are original game design. Every move currently uses procedural poses and shared combat primitives; authored clips are pending.", "", "## Characters", "", "| Character | Role | Playable | Techniques |", "|---|---|---|---|"]
    for c in data["characters"].values():
        lines.append(f'| {c["name"]} | {c["title"]} | {c["playable"]} | {len(c["moves"])} |')
    for style in data["styles"].values():
        lines += ["", "## " + style["name"], "", style["design"], "", "| Technique | Scope | Implementation | Reference |", "|---|---|---|---|"]
        for m in data["moves"].values():
            if m["style"] == style["id"]:
                scope = m["canon"] + ("; later-story" if m["spoiler"] else "")
                lines.append(f'| {m["name"]} | {scope} | {m["pattern"]}; {m["status"]} | [source]({data["sources"][m["source"]]["url"]}) |')
    (ROOT / "docs/CONTENT_INVENTORY.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f'Generated {len(data["characters"])} characters, {len(data["moves"])} techniques, {len(data["chapters"])} chapters.')

if __name__ == "__main__":
    generate()
